export const surpriseMePrompts = [

  "That moment when you finally understand a joke five minutes after everyone else has stopped laughing.",
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  "That moment when you realize it's Friday and you have no weekend plans.",
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  "That moment when you see the waiter coming with your food at a restaurant.",
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "That moment when you hit 'Send' on a message and immediately regret what you wrote.",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  "That moment when you find money in your pocket that you didn't know you had.",
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  "That moment when you spot a rainbow and feel a surge of happiness.",
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  "That moment when you wake up and realize it's a holiday and you can go back to sleep.",
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "That moment when you see your food coming at a restaurant.",
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  "That moment when you wake up just in time to see a beautiful sunrise.",
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  "That moment when you wake up minutes before your alarm goes off.",
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "That moment when you walk into a room and forget why you came in there in the first place.",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  "That moment when you finish a TV series and feel a mix of satisfaction and emptiness.",
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  "That moment when you realize it's your birthday and you forgot to plan anything.",
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  "That moment when you discover a new favorite food, and it becomes an obsession.",
  'A futuristic cyborg dance club, neon lights',  
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  "That moment when you successfully parallel park on the first try.",
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  "That moment when you see your favorite song playing and can't resist dancing.",
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  "That moment when you're about to sneeze, but it suddenly disappears.",
  'A Man falling in Love with his Computer, digital art',
  "That moment when you see someone you know in public and try to avoid eye contact.",
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  "That moment when you find the perfect GIF to express your feelings in a conversation.",  
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  "That moment when you accidentally send a text to the wrong person.",
  'A Space Shuttle flying above Cape Town, digital art',
  "That moment when you successfully fix a tech problem without calling for help.",
];






